(() => {
  'use strict';

  const $ = (selector) => document.querySelector(selector);
  const refs = {
    leftVenue: $('#left-venue'), rightVenue: $('#right-venue'), leftMarket: $('#left-market'), rightMarket: $('#right-market'),
    leftMarkets: $('#left-market-options'), rightMarkets: $('#right-market-options'), run: $('#run'), swap: $('#swap'), formula: $('#formula'), followLive: $('#follow-live'),
    intervals: $('#intervals'), ranges: $('#ranges'), copyApi: $('#copy-api'), canvas: $('#chart'), wrap: $('#chart-wrap'),
    tooltip: $('#chart-tooltip'), loading: $('#chart-loading'), empty: $('#chart-empty'), healthDot: $('#health-dot'),
    healthLabel: $('#health-label'), chartPair: $('#chart-pair'), chartSubtitle: $('#chart-subtitle'), observations: $('#observations-body'),
    alignment: $('#alignment-note'), entryZ: $('#entry-z'), exitZ: $('#exit-z'), entryLabel: $('#entry-z-label'), exitLabel: $('#exit-z-label'),
    upper: $('#upper-entry'), lower: $('#lower-entry'), exitWindow: $('#exit-window'), resetBands: $('#reset-bands'), toast: $('#toast'),
    volumeALegend: $('#volume-a-legend'), volumeBLegend: $('#volume-b-legend'), chartPulse: $('#chart-pulse')
  };

  const fallbackVenues = [
    ['binance_spot','Binance Spot'],['binance_perp','Binance Perpetual'],['bybit_spot','Bybit Spot'],['bybit_perp','Bybit Perpetual'],
    ['hyperliquid_perp','Hyperliquid'],['lighter_perp','Lighter'],['aster_perp','Aster'],['ondo_perp','Ondo Perps'],
    ['mexc_spot','MEXC Spot'],['mexc_perp','MEXC Perpetual'],['okx_spot','OKX Spot'],['okx_perp','OKX Perpetual']
  ].map(([id,label]) => ({id,label,intervals:['1m','5m','15m','30m','1h','4h','1d']}));
  const allIntervals = ['1m','3m','5m','15m','30m','1h','2h','4h','1d'];
  const query = new URLSearchParams(location.search);
  const configuredApiBase = query.get('api_base');
  const hostedApiBase = 'https://basis-lab-sg.onrender.com';
  const hostedPreview = location.hostname.endsWith('.github.io') || location.hostname==='josusanmartin.com' || location.pathname.startsWith('/basis-lab/');
  const staticPreview = query.get('static_demo') === '1';
  const apiBase = (configuredApiBase || (hostedPreview ? hostedApiBase : location.origin)).replace(/\/$/,'');
  const basisPointScale = 10_000;
  const state = {venues:fallbackVenues,interval:'1m',range:1,data:null,requestUrl:'',partialWindow:'',abort:null,visible:160,offset:0,hover:-1,drag:null,refreshTimer:null,live:{active:false,starting:false,generation:0,feeds:[],sources:{left:new Map(),right:new Map()},status:{left:'idle',right:'idle'},lastAligned:0,renderFrame:0,simulation:null,simulatedTicks:null}};
  const marketSearch = {left:{timer:null,abort:null,sequence:0,active:-1,items:[],open:false,selected:null,ignoreFocus:false},right:{timer:null,abort:null,sequence:0,active:-1,items:[],open:false,selected:null,ignoreFocus:false}};
  const metrics = {latest:$('#metric-latest'),mean:$('#metric-mean'),sigma:$('#metric-sigma'),z:$('#metric-z'),range:$('#metric-range'),direction:$('#metric-direction'),signal:$('#metric-signal')};

  function option(value,label){const element=document.createElement('option');element.value=value;element.textContent=label;return element}
  function populateVenues(){
    [refs.leftVenue,refs.rightVenue].forEach(select => {select.replaceChildren(...state.venues.map(v=>option(v.id,v.label)))});
    refs.leftVenue.value=queryValue('left_venue')||'bybit_perp'; refs.rightVenue.value=queryValue('right_venue')||'mexc_perp';
    refs.leftMarket.value=queryValue('left_market')||'WLFIUSDT'; refs.rightMarket.value=queryValue('right_market')||'WLFI_USDT';
    state.interval=queryValue('interval')||'1m'; state.range=Number(queryValue('range')||1);
    renderIntervals(); document.querySelectorAll('[data-range]').forEach(b=>b.classList.toggle('active',Number(b.dataset.range)===state.range));
  }
  function queryValue(name){return new URLSearchParams(location.search).get(name)}
  function venue(id){return state.venues.find(item=>item.id===id)||fallbackVenues.find(item=>item.id===id)}
  async function fetchApi(url,options={}){
    let response,lastError;
    for(let attempt=0;attempt<5;attempt++){
      try {response=await fetch(url,options);if(response.status!==404&&response.status<500)return response}
      catch(error){if(error.name==='AbortError')throw error;lastError=error}
      if(attempt<4)await new Promise(resolve=>setTimeout(resolve,250*(attempt+1)));
      if(options.signal?.aborted)throw new DOMException('Aborted','AbortError');
    }
    if(response)return response;throw lastError;
  }
  function renderIntervals(){
    const left=venue(refs.leftVenue.value)?.intervals||[],right=venue(refs.rightVenue.value)?.intervals||[];
    refs.intervals.replaceChildren(...allIntervals.map(name=>{const b=document.createElement('button');b.textContent=name.toUpperCase();b.dataset.interval=name;b.disabled=!left.includes(name)||!right.includes(name);b.classList.toggle('active',name===state.interval);return b}));
    if (refs.intervals.querySelector('.active:disabled')) {state.interval=[...refs.intervals.children].find(b=>!b.disabled)?.dataset.interval||'1h';renderIntervals()}
  }
  async function bootstrap(){
    try {if(staticPreview)throw new Error();const response=await fetchApi(`${apiBase}/api/v1/venues`,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error();state.venues=(await response.json()).data;refs.healthDot.className='online';refs.healthLabel.textContent='Live'}
    catch {refs.healthDot.className=staticPreview?'preview':'error';refs.healthLabel.textContent=staticPreview?'Static demo':'API offline'}
    populateVenues(); bind(); await Promise.all([loadMarkets('left'),loadMarkets('right')]);await compare();
    state.refreshTimer=setInterval(()=>{if(!document.hidden&&!state.live.active&&!state.live.starting)compare(true)},30000);
  }
  function bind(){
    refs.run.addEventListener('click',()=>compare());
    refs.followLive.addEventListener('click',()=>state.live.active?stopLive():startLive());
    document.addEventListener('keydown',event=>{if(event.key==='Enter'&&document.activeElement?.tagName!=='BUTTON')compare()});
    bindMarketPicker('left');bindMarketPicker('right');
    document.addEventListener('pointerdown',event=>{if(!event.target.closest('.market-field')){closeMarketMenu('left');closeMarketMenu('right')}});
    [refs.leftVenue,refs.rightVenue].forEach((select,index)=>select.addEventListener('change',()=>{stopLive({silent:true});const side=index?'right':'left',sourceSide=index?'left':'right',market=index?refs.rightMarket:refs.leftMarket;market.value='';marketSearch[side].selected=null;closeMarketMenu(side);renderIntervals();suggestEquivalent(sourceSide,side)}));
    refs.swap.addEventListener('click',()=>{stopLive({silent:true});[refs.leftVenue.value,refs.rightVenue.value]=[refs.rightVenue.value,refs.leftVenue.value];[refs.leftMarket.value,refs.rightMarket.value]=[refs.rightMarket.value,refs.leftMarket.value];[marketSearch.left.selected,marketSearch.right.selected]=[marketSearch.right.selected,marketSearch.left.selected];closeMarketMenu('left');closeMarketMenu('right');renderIntervals();loadMarkets('left');loadMarkets('right');compare()});
    refs.intervals.addEventListener('click',event=>{const button=event.target.closest('button:not(:disabled)');if(!button)return;state.interval=button.dataset.interval;renderIntervals();compare()});
    refs.ranges.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;state.range=Number(button.dataset.range);refs.ranges.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===button));compare()});
    refs.copyApi.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(state.requestUrl);toast('API URL copied')}catch{toast('Copy unavailable')}});
    [refs.entryZ,refs.exitZ].forEach(input=>input.addEventListener('input',()=>{updateBands();draw()}));
    refs.resetBands.addEventListener('click',()=>{refs.entryZ.value='2';refs.exitZ.value='.25';updateBands();draw()});
    addChartInteractions();
    new ResizeObserver(draw).observe(refs.wrap);
    window.addEventListener('beforeunload',()=>{stopLive({silent:true});state.abort?.abort();marketSearch.left.abort?.abort();marketSearch.right.abort?.abort();clearInterval(state.refreshTimer)},{once:true});
  }
  function marketPicker(side){return {select:side==='left'?refs.leftVenue:refs.rightVenue,input:side==='left'?refs.leftMarket:refs.rightMarket,list:side==='left'?refs.leftMarkets:refs.rightMarkets,search:marketSearch[side]}}
  function bindMarketPicker(side){
    const {input,list,search}=marketPicker(side);
    input.addEventListener('focus',()=>{if(search.ignoreFocus){search.ignoreFocus=false;return}loadMarkets(side,true,'')});
    input.addEventListener('input',()=>{stopLive({silent:true});search.selected=null;clearTimeout(search.timer);search.timer=setTimeout(()=>loadMarkets(side,true,input.value.trim()),140)});
    input.addEventListener('keydown',event=>{
      if(event.key==='ArrowDown'||event.key==='ArrowUp'){
        event.preventDefault();
        if(!search.open){openMarketMenu(side);if(!search.items.length)loadMarkets(side,true,'');}
        const delta=event.key==='ArrowDown'?1:-1,index=search.active<0?(delta>0?0:search.items.length-1):(search.active+delta+search.items.length)%Math.max(1,search.items.length);setActiveMarket(side,index);return;
      }
      if(event.key==='Enter'&&search.open){event.preventDefault();event.stopPropagation();if(search.items.length)selectMarket(side,search.active<0?0:search.active);return}
      if(event.key==='Escape'&&search.open){event.preventDefault();closeMarketMenu(side)}
    });
    list.addEventListener('pointerdown',event=>event.preventDefault());
    list.addEventListener('click',event=>{const row=event.target.closest('.market-option');if(row)selectMarket(side,Number(row.dataset.index))});
  }
  function openMarketMenu(side){const {input,list,search}=marketPicker(side);search.open=true;list.hidden=false;input.setAttribute('aria-expanded','true')}
  function closeMarketMenu(side){const {input,list,search}=marketPicker(side);search.open=false;search.active=-1;list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant')}
  function setActiveMarket(side,index){
    const {input,list,search}=marketPicker(side),rows=[...list.querySelectorAll('.market-option')];
    if(!rows.length){search.active=-1;return}
    search.active=Math.max(0,Math.min(index,rows.length-1));
    rows.forEach((row,rowIndex)=>{const active=rowIndex===search.active;row.classList.toggle('active',active);row.setAttribute('aria-selected',String(active))});
    input.setAttribute('aria-activedescendant',rows[search.active].id);rows[search.active].scrollIntoView({block:'nearest'});
  }
  function assetKey(value){const compact=String(value||'').replace(/[^a-z0-9]/gi,'').toUpperCase();return ({XBT:'BTC',WBTC:'BTC',WETH:'ETH',XDG:'DOGE',US500:'SP500',USA500:'SP500',SPX500:'SP500'})[compact]||compact}
  function inferredBase(venueId,symbol){const native=String(symbol||'').trim();if(venueId==='hyperliquid_perp')return native.split(':').at(-1)||'';if(venueId==='ondo_perp')return native.replace(/-USD\.P$/i,'');return ''}
  function currentBase(side){const {select,input,search}=marketPicker(side),native=input.value.trim(),selected=search.selected;if(selected&&selected.symbol.toUpperCase()===native.toUpperCase())return selected.base;return inferredBase(select.value,native)}
  function indexMarkets(venueId){if(venueId==='hyperliquid_perp')return[{symbol:'mkts:US500',normalized_symbol:'US500/USD',base:'US500',quote:'USD',active:true,match_reason:'known S&P 500 market'},{symbol:'xyz:SP500',normalized_symbol:'SP500/USD',base:'SP500',quote:'USD',active:true,match_reason:'known S&P 500 market'}];if(venueId==='ondo_perp')return[{symbol:'US500-USD.P',normalized_symbol:'US500/USD',base:'US500',quote:'USD',active:true,match_reason:'known S&P 500 market'}];return[]}
  function searchBase(value){const native=String(value||'').trim().split(':').at(-1).replace(/-USD\.P$/i,'');return assetKey(native)}
  function fallbackMarketResults(venueId,term){const native=String(term||'').trim();if(searchBase(native)==='SP500'){const markets=indexMarkets(venueId);if(native.includes(':'))return markets.filter(market=>market.symbol.toUpperCase()===native.toUpperCase());if(native.toUpperCase().startsWith('SP'))return markets.sort((left,right)=>Number(right.symbol.startsWith('xyz:'))-Number(left.symbol.startsWith('xyz:')));return markets}if(venueId==='hyperliquid_perp'&&/^[a-z0-9-]+:[a-z0-9._-]+$/i.test(native)){const [dex,coin]=native.split(':');return[{symbol:`${dex.toLowerCase()}:${coin.toUpperCase()}`,normalized_symbol:`${coin.toUpperCase()}/USD`,base:coin.toUpperCase(),quote:'USD',active:true,match_reason:'typed HIP-3 symbol'}]}return[]}
  function fallbackSuggestions(sourceSide,targetSide){return assetKey(currentBase(sourceSide))==='SP500'?indexMarkets(marketPicker(targetSide).select.value):[]}
  function pairValidationError(){if(staticPreview)return'';const left=assetKey(currentBase('left')),right=assetKey(currentBase('right'));if(!left||!right||left===right)return'';if((left==='SPX'&&right==='SP500')||(left==='SP500'&&right==='SPX'))return'Asset mismatch: Hyperliquid SPX is the SPX6900 token, not the S&P 500. Choose xyz:SP500 or mkts:US500.';return`Asset mismatch: ${left} and ${right} are different underlying assets. Choose equivalent tickers from the dropdown.`}
  function selectMarket(side,index){const {input,search}=marketPicker(side),market=search.items[index];if(!market)return;stopLive({silent:true});input.value=market.symbol;search.selected=market;closeMarketMenu(side);if(document.activeElement!==input){search.ignoreFocus=true;input.focus()}const targetSide=side==='left'?'right':'left',target=marketPicker(targetSide);if(!target.search.selected||assetKey(target.search.selected.base)!==assetKey(market.base))suggestEquivalent(side,targetSide)}
  function marketMessage(list,message){const row=document.createElement('div');row.className='market-option-state';row.setAttribute('role','option');row.setAttribute('aria-disabled','true');row.textContent=message;list.replaceChildren(row)}
  function renderMarketOptions(side,items){
    const {list,search}=marketPicker(side);search.items=items;search.active=-1;
    if(!items.length){marketMessage(list,'No matching markets');return}
    list.replaceChildren(...items.map((market,index)=>{const row=document.createElement('button'),primary=document.createElement('strong'),native=document.createElement('span');row.type='button';row.id=`${side}-market-option-${index}`;row.className='market-option';row.dataset.index=String(index);row.setAttribute('role','option');row.setAttribute('aria-selected','false');primary.textContent=market.normalized_symbol||market.symbol;native.textContent=market.match_reason?`${market.symbol} · ${market.match_reason}`:market.symbol===market.normalized_symbol?'Native symbol':market.symbol;if(market.requires_multiplier_check)row.classList.add('multiplier-check');row.append(primary,native);return row}));
  }
  async function suggestEquivalent(sourceSide,targetSide){
    const source=marketPicker(sourceSide),target=marketPicker(targetSide);if(!source.input.value.trim())return loadMarkets(targetSide,true,'');
    if(staticPreview)return loadMarkets(targetSide,true,'');
    target.search.abort?.abort();target.search.abort=new AbortController();const sequence=++target.search.sequence;openMarketMenu(targetSide);marketMessage(target.list,'Finding equivalent tickers…');
    try {const q=new URLSearchParams({source_venue:source.select.value,source_symbol:source.input.value.trim(),target_venue:target.select.value,limit:'8'}),response=await fetchApi(`${apiBase}/api/v1/tickers/suggest?${q}`,{signal:target.search.abort.signal,headers:{Accept:'application/json'}});if(!response.ok)throw new Error();let data=(await response.json()).data;if(sequence!==target.search.sequence)return;if(!data.length)data=fallbackSuggestions(sourceSide,targetSide);if(!data.length){marketMessage(target.list,'No equivalent ticker found');return}renderMarketOptions(targetSide,data);openMarketMenu(targetSide)}
    catch(error){if(error.name==='AbortError')return;if(sequence!==target.search.sequence)return;const data=fallbackSuggestions(sourceSide,targetSide);if(data.length){renderMarketOptions(targetSide,data);openMarketMenu(targetSide)}else loadMarkets(targetSide,true,target.input.value.trim())}
  }
  async function loadMarkets(side,open=false,term){
    const {select,input,list,search}=marketPicker(side);if(open)openMarketMenu(side);
    if(staticPreview){renderMarketOptions(side,[{symbol:input.value,normalized_symbol:input.value}]);return}
    search.abort?.abort();search.abort=new AbortController();const sequence=++search.sequence,query=term??input.value.trim();
    if(open)marketMessage(list,'Searching cached tickers…');
    try {const q=new URLSearchParams({venue:select.value,query,limit:'100'}),response=await fetchApi(`${apiBase}/api/v1/markets?${q}`,{signal:search.abort.signal,headers:{Accept:'application/json'}});if(!response.ok)throw new Error();let data=(await response.json()).data;if(sequence!==search.sequence)return;if(!data.length)data=fallbackMarketResults(select.value,query);search.selected=data.find(market=>market.symbol.toUpperCase()===input.value.trim().toUpperCase())||null;renderMarketOptions(side,data);if(search.open)openMarketMenu(side)}
    catch(error){if(error.name==='AbortError')return;if(sequence===search.sequence){marketMessage(list,'Market search unavailable');if(search.open)openMarketMenu(side)}}
  }
  function intervalMilliseconds(){return{ '1m':6e4,'3m':18e4,'5m':3e5,'15m':9e5,'30m':18e5,'1h':36e5,'2h':72e5,'4h':144e5,'1d':864e5}[state.interval]}
  function limits(){const to=Date.now(),from=to-state.range*864e5,step=intervalMilliseconds();return{from,to,limit:Math.min(1500,Math.ceil((to-from)/step)+4)}}
  function comparisonWindows(){const requested=limits();state.partialWindow='';if(state.interval!=='1m')return[requested];const earliest=Math.max(requested.from,requested.to-72*36e5);if(earliest>requested.from)state.partialWindow='latest 72 hours available';const windows=[];for(let from=earliest;from<requested.to;from+=864e5){const to=Math.min(requested.to,from+864e5);windows.push({from,to,limit:Math.min(1500,Math.ceil((to-from)/6e4)+4)})}return windows}
  function makeUrl(window=limits()){return `${apiBase}/api/v1/compare?${new URLSearchParams({left_venue:refs.leftVenue.value,left_market:refs.leftMarket.value.trim(),right_venue:refs.rightVenue.value,right_market:refs.rightMarket.value.trim(),interval:state.interval,from:String(window.from),to:String(window.to),limit:String(window.limit),scale:String(basisPointScale)})}`}
  function candleUrl(side,window){const picker=marketPicker(side);return`${apiBase}/api/v1/candles?${new URLSearchParams({venue:picker.select.value,market:picker.input.value.trim(),interval:state.interval,from:String(window.from),to:String(window.to),limit:String(window.limit)})}`}
  async function enrichComparisonVolumes(body,window){if(body.candles?.some(candle=>candle.left_volume!=null||candle.right_volume!=null))return body;const load=async side=>{try{const response=await fetchApi(candleUrl(side,window),{signal:state.abort.signal,headers:{Accept:'application/json'}});if(!response.ok)return[];return(await response.json()).candles||[]}catch(error){if(error.name==='AbortError')throw error;return[]}},[left,right]=await Promise.all([load('left'),load('right')]),leftByTime=new Map(left.map(candle=>[candle.time,candle.volume])),rightByTime=new Map(right.map(candle=>[candle.time,candle.volume]));body.candles?.forEach(candle=>{const leftVolume=leftByTime.get(candle.time),rightVolume=rightByTime.get(candle.time);if(Number.isFinite(leftVolume)&&leftVolume>=0)candle.left_volume=leftVolume;if(Number.isFinite(rightVolume)&&rightVolume>=0)candle.right_volume=rightVolume});return body}
  async function fetchComparison(window){let effectiveWindow=window,url=makeUrl(window),response=await fetchApi(url,{signal:state.abort.signal,headers:{Accept:'application/json'}}),body=await response.json().catch(()=>({}));if(!response.ok&&/maximal number of bars exceeded/i.test(body.error?.message||'')){const step=intervalMilliseconds();effectiveWindow={...window,from:Math.max(window.from,window.to-step*4899)};state.partialWindow='latest available venue window';url=makeUrl(effectiveWindow);response=await fetchApi(url,{signal:state.abort.signal,headers:{Accept:'application/json'}});body=await response.json().catch(()=>({}))}if(!response.ok)throw new Error(body.error?.message||`Request failed (${response.status})`);return{body:await enrichComparisonVolumes(body,effectiveWindow),url}}
  function comparisonStats(candles){const closes=candles.map(candle=>candle.close),mean=closes.reduce((sum,value)=>sum+value,0)/closes.length,variance=closes.reduce((sum,value)=>sum+(value-mean)**2,0)/closes.length,standard_deviation=Math.sqrt(variance),latest=closes.at(-1);return{latest,mean,standard_deviation,minimum:Math.min(...candles.map(candle=>candle.low)),maximum:Math.max(...candles.map(candle=>candle.high)),z_score:standard_deviation?(latest-mean)/standard_deviation:0}}
  function mergeComparisons(parts){if(parts.length===1)return parts[0];const template=parts.at(-1),byTime=new Map();parts.forEach(part=>part.candles.forEach(candle=>byTime.set(candle.time,candle)));const candles=[...byTime.values()].sort((left,right)=>left.time-right.time);return{...template,candles,matched_candles:candles.length,dropped_left:parts.reduce((sum,part)=>sum+part.dropped_left,0),dropped_right:parts.reduce((sum,part)=>sum+part.dropped_right,0),stats:comparisonStats(candles)}}
  function liveSuffix(){if(!state.live.active)return'';const ready=state.live.status.left==='streaming'&&state.live.status.right==='streaming',derived=state.live.derivedNotes?.length?` · ${state.live.derivedNotes.join(' · ')}`:'';if(ready&&state.live.lastAligned)return` · LIVE · WebSocket aligned ${new Date(state.live.lastAligned).toISOString().slice(11,19)} UTC${derived}`;return` · LIVE · A ${state.live.status.left} / B ${state.live.status.right}${derived}`}
  function updateLiveControls(){const active=state.live.active,starting=state.live.starting,label=refs.followLive.querySelector('span');refs.followLive.disabled=starting;refs.followLive.classList.toggle('active',active);refs.followLive.setAttribute('aria-pressed',String(active));label.textContent=starting?'Loading history…':active?'Stop live':'Follow live';refs.chartPulse.classList.toggle('live',active);if(active){refs.healthDot.className='online';refs.healthLabel.textContent=state.live.status.left==='streaming'&&state.live.status.right==='streaming'?'Following live':'Live connecting'}else if(staticPreview){refs.healthDot.className='preview';refs.healthLabel.textContent='Static demo'}else if(state.data){refs.healthDot.className='online';refs.healthLabel.textContent='Live'}}
  function stopLive({silent=false}={}){const wasRunning=state.live.active||state.live.starting;state.live.generation++;state.live.feeds.forEach(feed=>feed.close());state.live.feeds=[];clearInterval(state.live.simulation);state.live.simulation=null;state.live.simulatedTicks=null;if(state.live.renderFrame)cancelAnimationFrame(state.live.renderFrame);state.live.renderFrame=0;state.live.active=false;state.live.starting=false;state.live.sources={left:new Map(),right:new Map()};state.live.status={left:'idle',right:'idle'};state.live.lastAligned=0;state.live.derivedNotes=[];updateLiveControls();if(state.data)renderData();if(wasRunning&&!silent)toast('Live follow stopped')}
  function setLiveStatus(side,status,generation){if(generation!==state.live.generation||!state.live.active||state.live.status[side]===status)return;state.live.status[side]=status;updateLiveControls();if(state.data)renderData()}
  function websocketPayload(socket,payload){if(payload==null||socket.readyState!==WebSocket.OPEN)return;const value=typeof payload==='function'?payload():payload;socket.send(typeof value==='string'?value:JSON.stringify(value))}
  function createLiveFeed(side,descriptor,generation){let socket=null,retryTimer=null,heartbeatTimer=null,attempts=0,stopped=false;const clear=()=>{clearTimeout(retryTimer);clearInterval(heartbeatTimer);retryTimer=null;heartbeatTimer=null};const retry=()=>{if(stopped||generation!==state.live.generation)return;clear();setLiveStatus(side,'retrying',generation);const delay=Math.min(30_000,1000*2**Math.min(attempts++,5));retryTimer=setTimeout(connect,delay)};const connect=()=>{if(stopped||generation!==state.live.generation)return;setLiveStatus(side,attempts?'retrying':'connecting',generation);try{socket=new WebSocket(descriptor.url);if(descriptor.binaryType)socket.binaryType=descriptor.binaryType;socket.onopen=()=>{if(stopped)return;attempts=0;setLiveStatus(side,'connected',generation);websocketPayload(socket,descriptor.subscribe);if(descriptor.heartbeat)heartbeatTimer=setInterval(()=>websocketPayload(socket,descriptor.heartbeat),descriptor.heartbeatMs||20_000)};socket.onmessage=event=>{Promise.resolve(descriptor.parse(event.data)).then(candles=>{if(stopped||generation!==state.live.generation||!candles?.length)return;setLiveStatus(side,'streaming',generation);candles.forEach(candle=>ingestLiveCandle(side,candle,generation))}).catch(()=>{})};socket.onerror=()=>setLiveStatus(side,'retrying',generation);socket.onclose=retry}catch{retry()}};connect();return{close(){stopped=true;clear();if(socket&&socket.readyState<2)socket.close(1000,'Basis Lab live follow stopped');socket=null}}}
  function normalizeLiveCandle(raw){const step=intervalMilliseconds(),time=Math.floor(Number(raw.time)/step)*step,open=Number(raw.open),high=Number(raw.high),low=Number(raw.low),close=Number(raw.close),volume=Number(raw.volume);if(![time,open,high,low,close].every(Number.isFinite)||time<0||Math.min(open,high,low,close)<=0)return null;const candle={time,open,high:Math.max(high,open,close),low:Math.min(low,open,close),close};if(Number.isFinite(volume)&&volume>=0)candle.volume=volume;return candle}
  function compareLiveCandles(left,right){const open=(left.open/right.open-1)*basisPointScale,close=(left.close/right.close-1)*basisPointScale;return{time:left.time,open,high:Math.max((left.high/right.low-1)*basisPointScale,open,close),low:Math.min((left.low/right.high-1)*basisPointScale,open,close),close,left_close:left.close,right_close:right.close,...(Number.isFinite(left.volume)?{left_volume:left.volume}:{}),...(Number.isFinite(right.volume)?{right_volume:right.volume}:{})}}
  function scheduleLiveRender(){if(state.live.renderFrame)return;state.live.renderFrame=requestAnimationFrame(()=>{state.live.renderFrame=0;if(state.live.active&&state.data)renderData()})}
  function ingestLiveCandle(side,raw,generation){if(generation!==state.live.generation||!state.live.active||!state.data)return;const candle=normalizeLiveCandle(raw);if(!candle)return;const own=state.live.sources[side],other=state.live.sources[side==='left'?'right':'left'];own.set(candle.time,candle);while(own.size>8)own.delete(own.keys().next().value);const counterpart=other.get(candle.time);if(!counterpart)return;const left=side==='left'?candle:counterpart,right=side==='right'?candle:counterpart,comparison=compareLiveCandles(left,right),candles=state.data.candles,index=candles.findIndex(item=>item.time===comparison.time);if(index>=0){const existing=candles[index];candles[index]={...existing,...comparison,open:existing.open,high:Math.max(existing.high,comparison.high),low:Math.min(existing.low,comparison.low),...(comparison.left_volume==null&&existing.left_volume!=null?{left_volume:existing.left_volume}:{}),...(comparison.right_volume==null&&existing.right_volume!=null?{right_volume:existing.right_volume}:{})}}else{if(state.offset>0)state.offset++;candles.push(comparison);candles.sort((a,b)=>a.time-b.time);if(candles.length>1500)candles.splice(0,candles.length-1500)}state.data.matched_candles=candles.length;state.data.stats=comparisonStats(candles);state.live.lastAligned=Date.now();scheduleLiveRender()}
  function simulationTick(generation){if(generation!==state.live.generation||!state.live.active||!state.data)return;const last=state.data.candles.at(-1),step=intervalMilliseconds(),time=Math.floor(Date.now()/step)*step,ticks=state.live.simulatedTicks||(state.live.simulatedTicks={count:0,left:null,right:null}),phase=++ticks.count/5,leftPrice=(last?.left_close||1)*(1+Math.sin(phase)*.00008),rightPrice=(last?.right_close||1)*(1+Math.cos(phase*.83)*.00007);const update=(current,price,volume)=>!current||current.time!==time?{time,open:price,high:price,low:price,close:price,volume}:{...current,high:Math.max(current.high,price),low:Math.min(current.low,price),close:price,volume:current.volume+volume};ticks.left=update(ticks.left,leftPrice,4+Math.abs(Math.sin(phase))*7);ticks.right=update(ticks.right,rightPrice,3+Math.abs(Math.cos(phase))*6);ingestLiveCandle('left',ticks.left,generation);ingestLiveCandle('right',ticks.right,generation)}
  async function startLive(){if(state.live.starting||state.live.active)return;const validationError=pairValidationError();if(validationError)return toast(validationError);const generation=++state.live.generation;state.live.starting=true;updateLiveControls();await compare();if(generation!==state.live.generation)return;if(!state.data){state.live.starting=false;updateLiveControls();return}try{state.live.sources={left:new Map(),right:new Map()};state.live.status={left:'connecting',right:'connecting'};state.live.lastAligned=0;state.live.derivedNotes=[];if(staticPreview){state.live.active=true;state.live.starting=false;state.live.status={left:'streaming',right:'streaming'};updateLiveControls();simulationTick(generation);state.live.simulation=setInterval(()=>simulationTick(generation),700);renderData();return}const options=side=>{const picker=marketPicker(side);return{venue:picker.select.value,market:picker.input.value.trim(),interval:state.interval,intervalMillis:intervalMilliseconds()}},descriptors=await Promise.all([window.BasisLiveFeeds.descriptor(options('left')),window.BasisLiveFeeds.descriptor(options('right'))]);if(generation!==state.live.generation)return;state.live.active=true;state.live.starting=false;state.live.derivedNotes=descriptors.map((descriptor,index)=>descriptor.kind?`${index?'B':'A'} ${descriptor.kind}`:null).filter(Boolean);state.live.feeds=[createLiveFeed('left',descriptors[0],generation),createLiveFeed('right',descriptors[1],generation)];updateLiveControls();renderData();toast('Following both venue WebSockets')}catch(error){if(generation!==state.live.generation)return;stopLive({silent:true});toast(error.message||'Unable to start live feeds')}}
  function showComparisonError(message,dataError=false){state.data=null;refs.run.disabled=false;refs.loading.hidden=true;refs.empty.hidden=false;refs.empty.querySelector('strong').textContent='Comparison unavailable';refs.empty.querySelector('p').textContent=message;refs.chartPair.textContent=`${refs.leftMarket.value.trim()} / ${refs.rightMarket.value.trim()}`;refs.chartSubtitle.textContent=message;refs.alignment.textContent='Choose markets with the same normalized base asset';refs.volumeALegend.hidden=true;refs.volumeBLegend.hidden=true;[metrics.latest,metrics.mean,metrics.sigma,metrics.z,metrics.range,refs.upper,refs.lower,refs.exitWindow].forEach(element=>element.textContent='—');metrics.direction.textContent='No basis signal';metrics.signal.textContent='CHECK PAIR';refs.observations.replaceChildren();draw();if(dataError){refs.healthDot.className='error';refs.healthLabel.textContent='Data error'}toast(message)}
  async function compare(silent=false){
    if(state.live.active)stopLive({silent:true});
    if(!refs.leftMarket.value.trim()||!refs.rightMarket.value.trim())return toast('Choose both markets');
    const validationError=pairValidationError();if(validationError){state.abort?.abort();showComparisonError(validationError);return}
    state.abort?.abort();state.abort=new AbortController();const windows=comparisonWindows();state.requestUrl=makeUrl(windows[0]);
    refs.run.disabled=true;if(!silent){refs.loading.hidden=false;refs.empty.hidden=true}
    try {
      if(staticPreview){state.data=previewData();state.visible=Math.min(state.data.candles.length,Math.max(80,Math.round(refs.wrap.clientWidth/7)));state.offset=0;state.hover=-1;updateUrl();renderData();refs.healthDot.className='preview';refs.healthLabel.textContent='Static demo';return}
      const results=await Promise.all(windows.map(fetchComparison)),body=mergeComparisons(results.map(result=>result.body));state.requestUrl=results.at(-1).url;
      state.data=body;state.visible=Math.min(body.candles.length,Math.max(80,Math.round(refs.wrap.clientWidth/7)));state.offset=0;state.hover=-1;
      updateUrl();renderData();refs.healthDot.className='online';refs.healthLabel.textContent='Live';
    } catch(error) {if(error.name==='AbortError')return;showComparisonError(error.message,true)}
    finally {refs.loading.hidden=true;refs.run.disabled=false}
  }
  function updateUrl(){const params=new URLSearchParams({left_venue:refs.leftVenue.value,left_market:refs.leftMarket.value.trim(),right_venue:refs.rightVenue.value,right_market:refs.rightMarket.value.trim(),interval:state.interval,range:String(state.range)});if(configuredApiBase)params.set('api_base',configuredApiBase);if(staticPreview)params.set('static_demo','1');history.replaceState(null,'',`${location.pathname}?${params}`)}
  function previewData(){
    const {from,to,limit}=limits(),step={'1m':6e4,'3m':18e4,'5m':3e5,'15m':9e5,'30m':18e5,'1h':36e5,'2h':72e5,'4h':144e5,'1d':864e5}[state.interval],count=Math.min(limit,220),seed=[...`${refs.leftVenue.value}:${refs.leftMarket.value}:${refs.rightVenue.value}:${refs.rightMarket.value}`].reduce((sum,char)=>sum+char.charCodeAt(0),0),end=Math.floor(to/step)*step;
    const candles=Array.from({length:count},(_,index)=>{const time=Math.max(from,end-(count-1-index)*step),center=Math.sin((index+seed)/11)*18+Math.cos((index+seed)/29)*7,open=center+Math.sin(index*.73)*3,close=center+Math.cos(index*.51)*3.2,leftClose=1+seed/10000+index/100000;return {time,open,high:Math.max(open,close)+4.4,low:Math.min(open,close)-4.4,close,left_close:leftClose,right_close:leftClose/(1+close/10000),left_volume:900+Math.abs(Math.sin(index/8))*3200,right_volume:750+Math.abs(Math.cos(index/11))*2800}}),closes=candles.map(c=>c.close),mean=closes.reduce((a,b)=>a+b,0)/closes.length,variance=closes.reduce((sum,value)=>sum+(value-mean)**2,0)/closes.length,standard_deviation=Math.sqrt(variance),latest=closes.at(-1);
    return {interval:state.interval,unit:'basis points · illustrative static data',scale:basisPointScale,matched_candles:count,dropped_left:0,dropped_right:0,candles,stats:{latest,mean,standard_deviation,minimum:Math.min(...closes),maximum:Math.max(...closes),z_score:(latest-mean)/standard_deviation}}
  }
  function renderData(){
    const data=state.data,stats=data.stats,left=refs.leftMarket.value.trim(),right=refs.rightMarket.value.trim(),scale=Number(data.scale)||basisPointScale;
    refs.toast.classList.remove('show');
    refs.formula.textContent=`(${venue(refs.leftVenue.value).label}:${left} ÷ ${venue(refs.rightVenue.value).label}:${right} − 1) × ${scale.toLocaleString('en-US')}`;
    refs.chartPair.textContent=`${left} / ${right}`;refs.chartSubtitle.textContent=`${data.candles.length.toLocaleString()} aligned ${data.interval} candles · ${data.unit}${state.partialWindow?` · ${state.partialWindow}`:''}${liveSuffix()}`;
    refs.volumeALegend.hidden=!data.candles.some(candle=>Number.isFinite(candle.left_volume));refs.volumeBLegend.hidden=!data.candles.some(candle=>Number.isFinite(candle.right_volume));
    setMetric(metrics.latest,formatBps(stats.latest),stats.latest);setMetric(metrics.mean,formatBps(stats.mean),stats.mean);metrics.sigma.textContent=`${Math.abs(stats.standard_deviation).toFixed(1)} bp`;setMetric(metrics.z,`${stats.z_score>=0?'+':''}${stats.z_score.toFixed(2)}σ`,stats.z_score);
    metrics.range.textContent=`${stats.minimum.toFixed(0)} → ${stats.maximum.toFixed(0)}`;metrics.direction.textContent=stats.latest>=0?'A trades at a premium':'A trades at a discount';metrics.signal.textContent=signal(stats.latest).label;
    refs.alignment.textContent=`${data.matched_candles} matched · ${data.dropped_left} A-only · ${data.dropped_right} B-only${state.partialWindow?` · ${state.partialWindow}`:''}${state.live.active&&state.live.lastAligned?' · live bar aligned':''}`;
    updateBands();renderTable();refs.empty.hidden=!!data.candles.length;draw();
  }
  function setMetric(element,text,value){element.textContent=text;element.classList.toggle('positive',value>0);element.classList.toggle('negative',value<0)}
  function formatBps(value){return `${value>=0?'+':''}${value.toFixed(Math.abs(value)>=100?0:1)} bp`}
  function thresholds(){if(!state.data)return null;const {mean,standard_deviation:s}=state.data.stats,entry=Number(refs.entryZ.value),exit=Number(refs.exitZ.value);return {upper:mean+entry*s,lower:mean-entry*s,exitUpper:mean+exit*s,exitLower:mean-exit*s,mean}}
  function updateBands(){refs.entryLabel.textContent=`${Number(refs.entryZ.value).toFixed(2).replace(/0$/,'')}σ`;refs.exitLabel.textContent=`${Number(refs.exitZ.value).toFixed(2).replace(/0$/,'')}σ`;const t=thresholds();if(!t)return;refs.upper.textContent=formatBps(t.upper);refs.lower.textContent=formatBps(t.lower);refs.exitWindow.textContent=`${t.exitLower.toFixed(1)} to ${t.exitUpper.toFixed(1)} bp`}
  function signal(value){const t=thresholds();if(!t)return {label:'NEUTRAL',className:''};if(value>=t.upper)return {label:'SHORT A / LONG B',className:'short'};if(value<=t.lower)return {label:'LONG A / SHORT B',className:'long'};if(value>=t.exitLower&&value<=t.exitUpper)return {label:'EXIT WINDOW',className:''};return {label:'WATCH',className:''}}
  function renderTable(){const rows=state.data.candles.slice(-12).reverse();refs.observations.replaceChildren(...rows.map(c=>{const tr=document.createElement('tr'),sig=signal(c.close);[new Date(c.time).toISOString().replace('T',' ').slice(0,16),formatBps(c.close),`${c.low.toFixed(1)} — ${c.high.toFixed(1)}`,price(c.left_close),price(c.right_close)].forEach(value=>{const td=document.createElement('td');td.textContent=value;tr.append(td)});const td=document.createElement('td'),pill=document.createElement('span');pill.className=`signal-pill ${sig.className}`;pill.textContent=sig.label;td.append(pill);tr.append(td);return tr}))}
  function price(value){return value>=1000?value.toLocaleString(undefined,{maximumFractionDigits:2}):value.toLocaleString(undefined,{maximumSignificantDigits:8})}
  function visibleCandles(){if(!state.data)return[];const all=state.data.candles,count=Math.min(state.visible,all.length),end=Math.max(count,all.length-state.offset),start=Math.max(0,end-count);return all.slice(start,end)}
  function draw(){
    const canvas=refs.canvas,rect=refs.wrap.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);if(rect.width<10||rect.height<10)return;canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);
    const candles=visibleCandles();if(!candles.length)return;const pad={top:18,right:63,bottom:31,left:8},w=rect.width-pad.left-pad.right,h=rect.height-pad.top-pad.bottom,t=thresholds(),volumePanels=[];if(candles.some(candle=>Number.isFinite(candle.left_volume)))volumePanels.push({field:'left_volume',label:'A VOLUME',color:'rgba(107,140,255,.62)',background:'rgba(107,140,255,.025)'});if(candles.some(candle=>Number.isFinite(candle.right_volume)))volumePanels.push({field:'right_volume',label:'B VOLUME',color:'rgba(167,132,255,.62)',background:'rgba(167,132,255,.025)'});const volumePanelGap=volumePanels.length>1?7:0,priceVolumeGap=volumePanels.length?14:0,volumePanelHeight=volumePanels.length?Math.min(54,h*(volumePanels.length>1?.13:.2)):0,volumeAreaHeight=volumePanels.length*volumePanelHeight+(volumePanels.length-1)*volumePanelGap,priceHeight=h-priceVolumeGap-volumeAreaHeight;let min=Math.min(...candles.map(c=>c.low),t?.lower??Infinity,t?.exitLower??Infinity),max=Math.max(...candles.map(c=>c.high),t?.upper??-Infinity,t?.exitUpper??-Infinity);const margin=Math.max((max-min)*.08,1);min-=margin;max+=margin;const y=v=>pad.top+(max-v)/(max-min)*priceHeight,x=i=>pad.left+(i+.5)/candles.length*w;
    ctx.font='9px "DM Mono",monospace';ctx.textAlign='left';ctx.textBaseline='middle';for(let i=0;i<=5;i++){const yy=pad.top+priceHeight*i/5,value=max-(max-min)*i/5;ctx.strokeStyle='#1c222b';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(pad.left,yy+.5);ctx.lineTo(pad.left+w,yy+.5);ctx.stroke();ctx.fillStyle='#697483';ctx.fillText(`${value.toFixed(Math.abs(value)>100?0:1)}`,pad.left+w+8,yy)}
    const band=(value,color,dash=[])=>{const yy=y(value);ctx.save();ctx.strokeStyle=color;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(pad.left,yy);ctx.lineTo(pad.left+w,yy);ctx.stroke();ctx.restore()};
    if(t){ctx.fillStyle='rgba(200,255,100,.025)';ctx.fillRect(pad.left,y(t.exitUpper),w,y(t.exitLower)-y(t.exitUpper));band(t.upper,'rgba(255,107,122,.42)',[4,5]);band(t.lower,'rgba(98,239,189,.42)',[4,5]);band(t.mean,'rgba(150,160,175,.6)',[2,4])}if(min<=0&&max>=0)band(0,'rgba(200,255,100,.22)');
    const step=w/candles.length,body=Math.max(1,Math.min(step*.66,9));candles.forEach((c,i)=>{const xx=x(i),up=c.close>=c.open,color=up?'#62efbd':'#ff6b7a';ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(Math.round(xx)+.5,y(c.high));ctx.lineTo(Math.round(xx)+.5,y(c.low));ctx.stroke();const top=y(Math.max(c.open,c.close)),bottom=y(Math.min(c.open,c.close));ctx.fillRect(xx-body/2,top,body,Math.max(1,bottom-top))});
    const drawVolumePanel=(panel,top)=>{const values=candles.map(candle=>candle[panel.field]).filter(Number.isFinite),maximum=Math.max(0,...values),scale=maximum||1,bottom=top+volumePanelHeight,plotTop=top+14,plotHeight=Math.max(1,bottom-plotTop-1),barWidth=Math.max(1,Math.min(step*.66,9));ctx.fillStyle=panel.background;ctx.fillRect(pad.left,top,w,volumePanelHeight);ctx.strokeStyle='#242b35';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(pad.left,top+.5);ctx.lineTo(pad.left+w,top+.5);ctx.moveTo(pad.left,Math.round(plotTop+plotHeight/2)+.5);ctx.lineTo(pad.left+w,Math.round(plotTop+plotHeight/2)+.5);ctx.moveTo(pad.left,bottom-.5);ctx.lineTo(pad.left+w,bottom-.5);ctx.stroke();ctx.fillStyle=panel.color;ctx.textAlign='left';ctx.fillText(panel.label,pad.left+4,top+8);ctx.fillStyle='#657080';ctx.fillText(formatVolume(maximum),pad.left+w+8,top+8);candles.forEach((candle,index)=>{const volume=Number.isFinite(candle[panel.field])?candle[panel.field]:0;if(volume<=0)return;const height=volume/scale*plotHeight;ctx.fillStyle=panel.color;ctx.fillRect(x(index)-barWidth/2,bottom-height-1,barWidth,height)})};
    volumePanels.forEach((panel,index)=>drawVolumePanel(panel,pad.top+priceHeight+priceVolumeGap+index*(volumePanelHeight+volumePanelGap)));
    const ticks=Math.min(rect.width<500?3:6,candles.length);for(let i=0;i<ticks;i++){const index=Math.round(i*(candles.length-1)/Math.max(1,ticks-1)),xx=x(index);ctx.fillStyle='#657080';ctx.textAlign=i===0?'left':i===ticks-1?'right':'center';ctx.fillText(timeLabel(candles[index].time,state.range),xx,pad.top+h+18)}
    if(state.hover>=0&&state.hover<candles.length){const c=candles[state.hover],xx=x(state.hover);ctx.strokeStyle='rgba(180,190,203,.35)';ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(xx,pad.top);ctx.lineTo(xx,pad.top+h);ctx.stroke();ctx.setLineDash([]);showTooltip(c,xx,y(c.close),rect)}else refs.tooltip.hidden=true;
  }
  function timeLabel(timestamp,range){const d=new Date(timestamp);return range<=1?d.toISOString().slice(11,16):range<=7?`${d.toISOString().slice(5,10)} ${d.toISOString().slice(11,16)}`:d.toISOString().slice(5,10)}
  function formatVolume(value){return Number.isFinite(value)?value.toLocaleString(undefined,{notation:'compact',maximumFractionDigits:2}):'—'}
  function showTooltip(c,x,y,rect){refs.tooltip.hidden=false;refs.tooltip.replaceChildren();const strong=document.createElement('strong');strong.textContent=`${new Date(c.time).toISOString().slice(0,16).replace('T',' ')} UTC`;refs.tooltip.append(strong);[['O',formatBps(c.open)],['H',formatBps(c.high)],['L',formatBps(c.low)],['C',formatBps(c.close)],['A vol',formatVolume(c.left_volume)],['B vol',formatVolume(c.right_volume)]].forEach(([label,value])=>{if(value==='—'&&(label==='A vol'||label==='B vol'))return;const row=document.createElement('div'),a=document.createElement('span'),b=document.createElement('span');a.textContent=label;b.textContent=value;row.append(a,b);refs.tooltip.append(row)});refs.tooltip.style.left=`${Math.min(rect.width-190,Math.max(8,x+13))}px`;refs.tooltip.style.top=`${Math.min(rect.height-150,Math.max(8,y-74))}px`}
  function addChartInteractions(){
    refs.canvas.addEventListener('pointermove',event=>{const rect=refs.canvas.getBoundingClientRect(),candles=visibleCandles(),right=63,left=8,index=Math.floor((event.clientX-rect.left-left)/(rect.width-left-right)*candles.length);state.hover=Math.max(-1,Math.min(candles.length-1,index));if(state.drag){const delta=Math.round((event.clientX-state.drag.x)/(rect.width-left-right)*state.visible);state.offset=Math.max(0,Math.min(state.data.candles.length-state.visible,state.drag.offset+delta))}draw()});
    refs.canvas.addEventListener('pointerleave',()=>{state.hover=-1;state.drag=null;draw()});
    refs.canvas.addEventListener('pointerdown',event=>{if(!state.data)return;refs.canvas.setPointerCapture(event.pointerId);state.drag={x:event.clientX,offset:state.offset}});
    refs.canvas.addEventListener('pointerup',()=>{state.drag=null});
    refs.canvas.addEventListener('wheel',event=>{if(!state.data)return;event.preventDefault();const factor=event.deltaY>0?1.14:.86;state.visible=Math.max(20,Math.min(state.data.candles.length,Math.round(state.visible*factor)));state.offset=Math.min(state.offset,Math.max(0,state.data.candles.length-state.visible));draw()},{passive:false});
    refs.canvas.addEventListener('dblclick',()=>{if(!state.data)return;state.visible=Math.min(state.data.candles.length,Math.max(80,Math.round(refs.wrap.clientWidth/7)));state.offset=0;draw()});
  }
  function toast(message){refs.toast.textContent=message;refs.toast.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>refs.toast.classList.remove('show'),2200)}
  bootstrap();
})();
